text = "";
text_arr = -4;
text_size = [0, 0];
fadeout = false;
fade = 0;
SCREEN_WIDTH = display_get_gui_width()
SCREEN_HEIGHT =	display_get_gui_height()
visible = false;
alarm[0] = 1;
alarm[1] = 220;
depth = -499;
