scr_fakepep_init_sounds();
hsp = 0;
vsp = 0;
grav = 0.5;
platformid = -4;
hsp_carry = 0;
vsp_carry = 0;
paletteselect = 0;
bodyslam = false;
flash = false;
hitboxID = -4;
attack = -4;
attacked = false;
spawnerID = -4;
throwing = false;
attackspeed = 0;
state = states.transition;
headID = -4;
cooldown = 0;
scr_soundeffect(sfx_fakepepreform)
sprite_index = spr_fakepeppino_reform;
image_index = 0;
image_speed = 0.35;
