wave_x = 0
crosshair_x = x
crosshair_y = y
wave_xlimit = 156
turn = 1
shoot_max = 125
saved_xs = ((!global.panic) ? 1 : -1)
state = states.normal
image_speed = 0.35
depth = -8
captain_x = -37
captain_y = 550
captain_xto = 234
captain_yto = 367
captain_index = 0
captain_sprite = spr_captainbomb
destroyed = 0
